### ISSUE TITLE
Scale path generated by path.arcTo() or path.arc()

### ISSUE THREAD

**Issue by kuy** [d3/d3-path#6]
Hi, I'm working with D3 v4 and writing a function that draws a path with a rounded corner.
My problem is how to scale (translate?) a path with arc segment.

For example, here is a function without scaling. (at [codepen](http://codepen.io/netkuy/pen/bpXVqJ?editors=0010))
```
const context = d3.path();
context.moveTo(50, 50);
context.lineTo(100, 50);
context.arc(100, 100, 50, -0.5 * Math.PI, 0);
context.lineTo(150, 150);
```

I introduced scale functions to get a feature of zooming in/out.
The functions are used globally, I have to apply them to the draw function. (at [codepen](http://codepen.io/netkuy/pen/vGoNjz?editors=0010))
```
const x = d3.scaleLinear()...;
const y = d3.scaleLinear()...;

const context = d3.path();
context.moveTo(x(50), y(50));
context.lineTo(x(100), y(50));
context.arc(x(100), y(100), ???, -0.5 * Math.PI, 0); // how to scale radius?
context.lineTo(x(150), y(150));
```

Is there way to scale `radius` parameter in `arc()` or `arcTo()` method?

**Comment by mbostock** [comment]
The d3-path module simply provides an implementation of the [CanvasPathMethods](https://www.w3.org/TR/2dcontext/#canvaspathmethods) (part of the Canvas 2D Context API) that serializes to SVG path data; this is so that you can write code that renders to either Canvas or SVG. Please read the W3C specifications to learn more about the standard APIs.

If you want to use D3 to render shapes, such as src segments, I recommend taking a look at the [d3-shape module](https://github.com/d3/d3-shape). The d3-path module is primarily intended as an implementation aid for reusable D3 modules and plugins, and not to be used directly. (If you’re using it directly, it’s probably easier to just pick either Canvas or SVG, and use that.)

**Comment by kuy** [comment]
Thank you for pointing a reference!
